name: Terraform Deploy and Destroy
on:
  push:
    branches:
      - main

  workflow_dispatch:  # Enables manual trigger for destroy job

env:
  AWS_REGION: eu-west-1  # You can update this if needed

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        working-directory: environments/dev

  destroy:
    name: Terraform Destroy (Manual Trigger + Approval)
    runs-on: ubuntu-latest
    needs: terraform  # Waits for apply to complete
    if: github.event_name == 'workflow_dispatch'  # Only runs when triggered manually
    environment:
      name: dev-destroy  # Create this environment in GitHub Settings for approval
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: environments/dev
