name: Terraform Deploy and Destroy

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Enables manual trigger for destroy job


jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform Init
        run: terraform init
        working-directory: Azure

      - name: Terraform Plan
        run: terraform plan 
        working-directory: Azure

      - name: Terraform Apply
        run: terraform apply -auto-approve 
        working-directory: Azure

  destroy:
    name: Terraform Destroy (Manual Trigger + Approval)
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: dev-destroy
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform Init
        run: terraform init
        working-directory: Azure

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
        working-directory: Azure
