name: Terraform Destroy

on:
  workflow_dispatch:  # Enables manual trigger


env:
  AWS_REGION: eu-west-1  # Update as needed

jobs:
  destroy:
    name: Terraform Destroy (Manual Trigger + Approval)
    runs-on: ubuntu-latest
    environment:
      name: dev-destroy  # Optional: use for GitHub Environment approval
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: environments/dev

#testing
